In [44]:
from pylab import *
from scipy.optimize import curve_fit
from scipy.stats import chi2
fname = sys.argv[1] if len(sys.argv) > 1 else 'data.txt'
file=np.genfromtxt('test.txt',dtype='float')
x=file[:,0]
y=file[:,1]
err=file[:,2]

n = len(x) # the number of data points
p0 = [-0.25, 0.2, 2.8] # initial values of parameters
f = lambda x, Tc, w, A: Tc + A/x**w # define the function to be fitted
# note python’s lambda notation

p, covm = curve_fit(f, x, y, p0, err) # do the fit
Tc, w, A = p
chisq = sum(((f(x, Tc, w, A) - y)/err)**2) # compute the chi-squared
ndf = n -len(p) # no. of degrees of freedom
Q = 1. - chi2.cdf(chisq, ndf) # compute the quality of fit parameter Q
75
chisq = chisq / ndf # compute chi-squared per DOF
Tcerr, werr, Aerr = sqrt(diag(covm)/chisq) # correct the error bars
print('Tc = %10.4f +/- %7.4f' % (Tc, Tcerr))
print ('A = %10.4f +/- %7.4f' % (A, Aerr))
# print ’w = %10.4f +/- %7.4f’ % (w, werr)
# print ’chi squared / NDF = %7.4lf’ % chisq
# print ’Q = %10.4f’ % Q


Tc =    -0.2570 +/-  1.4775
A =     2.7878 +/-  0.8250


In [50]:
from pylab import *
from scipy.optimize import curve_fit
from scipy.stats import chi2
fname = sys.argv[1] if len(sys.argv) > 1 else 'data.txt'
file=np.genfromtxt('test.txt',dtype='float')
x=file[:,0]
y=file[:,1]
err=file[:,2]

n = len(x) # the number of data points
p0 = [0.1, 0.1, 0.1, 0.1] # initial values of parameters
f = lambda x, a3,a2,a1,a0: a3*x^2+a2*x^2+a1*x+a0 # define the function to be fitted
# note python’s lambda notation
p, covm = curve_fit(f, x, y) # do the fit
# a3,a2,a1,a0 = p
# chisq = sum(((f(x, a3,a2,a1,a0) - y)/err)**2) # compute the chi-squared
# ndf = n -len(p) # no. of degrees of freedom
# Q = 1. - chi2.cdf(chisq, ndf) # compute the quality of fit parameter Q
# 75
# chisq = chisq / ndf # compute chi-squared per DOF
# Tcerr, werr, Aerr = sqrt(diag(covm)/chisq) # correct the error bars
# # print('Tc = %10.4f +/- %7.4f' % (Tc, Tcerr))
# # print ('A = %10.4f +/- %7.4f' % (A, Aerr))
# # print ’w = %10.4f +/- %7.4f’ % (w, werr)
# # print ’chi squared / NDF = %7.4lf’ % chisq
# # print ’Q = %10.4f’ % Q


TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [66]:
import numpy as np
#dataframe = pd.read_fwf('test.txt')
#x, y, err = np.loadtxt('test.txt', delimiter=" ") # read in the data
a=np.genfromtxt('datos_grafica2.txt',dtype='float')
x=a[:,0]
y=a[:,1]
p,cov = polyfit(x,y,3,cov=True)
print(p)
#print(cov)
print (sqrt(diag(cov)))

[-0.00709677  0.22228584 -3.05056347  1.23053155]
[0.00254591 0.04245644 0.20583331 0.27461011]


In [73]:
import numpy as np
#dataframe = pd.read_fwf('test.txt')
#x, y, err = np.loadtxt('test.txt', delimiter=" ") # read in the data
a=np.genfromtxt('datos_grafica1_25.txt',dtype='float')
x=a[:,0]
y=a[:,0]
p,cov = polyfit(x,y,3,cov=True)
print(p)
#print(cov)
print (sqrt(diag(cov)))

[ 1.81249398e-16 -1.59898343e-15  1.00000000e+00 -3.92191571e-15]
[2.25767822e-17 2.04477072e-16 5.50905209e-16 4.21454769e-16]


In [76]:
import numpy as np
#dataframe = pd.read_fwf('test.txt')
#x, y, err = np.loadtxt('test.txt', delimiter=" ") # read in the data
a=np.genfromtxt('datos_grafica1_3.txt',dtype='float')
x=a[:,0]
y=a[:,0]
p,cov = polyfit(x,y,3,cov=True)
print(p)
#print(cov)
print (sqrt(diag(cov)))

[ 1.81249398e-16 -1.59898343e-15  1.00000000e+00 -3.92191571e-15]
[2.25767822e-17 2.04477072e-16 5.50905209e-16 4.21454769e-16]


In [80]:
import numpy
from kapteyn import kmpfit

def residuals(p, data):  # Residuals function needed by kmpfit
   x, y = data           # Data arrays is a tuple given by programmer
   a, b = p              # Parameters which are adjusted by kmpfit
   return (y-(a+b*x))

d = numpy.array([42, 6.75, 25, 33.8, 9.36, 21.8, 5.58, 8.52, 15.1])
v = numpy.array([1294, 462, 2562, 2130, 750, 2228, 598, 224, 971])

paramsinitial = [0, 70.0]
fitobj = kmpfit.Fitter(residuals=residuals, data=(d,v))
fitobj.fit(params0=paramsinitial)

ModuleNotFoundError: No module named 'kapteyn'